### ISSUE TITLE
[Request] Add option to apply override for all websites

### ISSUE THREAD

**Issue by emvaized** [bramus/chrome-dark-mode-toggle#2]
I would like to override color theme on any website I visit, without the need to click on extension icon every time. Would be nice to see an option for this in the extension.

**Comment by bramus** [comment]
Yes, this is [how I envision browser-level dark mode toggles should work](https://www.bram.us/2022/05/25/dark-mode-toggles-should-be-a-browser-feature/#inherited-settings). This feature was skipped for v1, and should be added later.

**Comment by bramus** [comment]
Took a stab at this and it turned out to be quite easy … version 1.1.0 has been submitted to the Chrome Web Store and should be published soon.

**Comment by emvaized** [comment]
> Took a stab at this and it turned out to be quite easy … version 1.1.0 has been submitted to the Chrome Web Store and should be published soon.

Thanks a lot! 🙏
