### ISSUE TITLE
[Suggestion] Run content script at document start

### ISSUE THREAD

**Issue by emvaized** [bramus/chrome-dark-mode-toggle#3]
I noticed that this extension applies content scripts on document load end. It probably makes sense to apply them on document start by adding `"run_at": "document_start"` line to the `content_scripts` section of the `manifest.json` file.

**Comment by bramus** [comment]
Good catch! Didn’t know this option existed.

Added in 1.0.1 which I have submitted just now to the Chrome Web Store. Should be published soon.
