### ISSUE TITLE
Avoid dependency on experimental Web Platform features?

### ISSUE THREAD

**Issue by mathiasbynens** [bramus/chrome-dark-mode-toggle#4]
> This extension uses the [Web Preferences API](https://wicg.github.io/web-preferences-api/), an API that is currently only available in Chrome 125+ with the Experimental Web Platform Features flag enabled.

To avoid this dependency, you could declare [the `"debugger"` permission in your extension’s manifest](https://developer.chrome.com/docs/extensions/reference/api/debugger) and use [CDP `Emulation.setEmulatedMedia`](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setEmulatedMedia) to force light/dark mode.

**Comment by bramus** [comment]
I have actually tried that approach in a v0 version of the extension. It was very buggy to get it working correctly (as in: the connection to the page sometimes dropped) + it also caused a “this site is being controlled by DevTools” (or something like that) banner to appear on every page.

It would also no longer play nice with the Web Preferences API when sites use that _(which, today, is only 1 single site so far)_.

Ideally, the Web Preferences API gets unflagged, or this feature would get built into Chrome itself :)

**Comment by mathiasbynens** [comment]
I see!
